spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/dangoDB
    username: ENC(wCGNI07D94baaXkkFlE4uz11xQpsPBEv)
    password: ENC(VFURZq/xW7Fn76tf88z2x1XQnuf+I6f7)
  jpa:
    hibernate:
      ddl-auto: none
      defer-datasource-initialization: true
      database-platform: org.hibernate.dialect.MySQLDialect
      show-sql: false
    properties:
      hibernate:
        format_sql: true
        show_sql: true
  mail:
    host: smtp.naver.com
    port: 465
    username: ${mail.username}
    password: ${mail.password}
    properties:
      mail:
        smtp:
          auth: true
          ssl:
            enable: true
          starttls:
            enable: true
logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: trace
  thymeleaf:
    cache: false
server:
  error:
    whitelabel:
      enabled: false
jasypt:
  encryptor:
    bean: jasyptStringEncryptor
    password: ${encrypt-password}