spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/dangoDB
    username: ENC(wCGNI07D94baaXkkFlE4uz11xQpsPBEv)
    password: ENC(VFURZq/xW7Fn76tf88z2x1XQnuf+I6f7)
  jpa:
    hibernate:
      ddl-auto: none
      defer-datasource-initialization: true
      database-platform: org.hibernate.dialect.MySQLDialect
      show-sql: false
  thymeleaf:
    cache: false
jasypt:
  encryptor:
    bean: jasyptStringEncryptor
    password: ${encrypt-password}
logging:
  level:
    root: debug